name: publish-core
description: Core NPM publish

inputs:
  token:
    description: NPM Token
    required: true
  version:
    description: Release version
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.version }}
    - run: yarn --ignore-scripts
      name: Install dependencies
    - run: yarn compile
      name: Compile smart contracts
      working-directory: ./packages/core
    - uses: JS-DevTools/npm-publish@v1
      with:
        package: ./packages/core/package.json
        access: public
        token: ${{ inputs.token }}
