name: publish-node-sdk
description: Node.js SDK NPM publish

inputs:
  token:
    description: NPM Token
    required: true
  version:
    description: Release version
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.version }}
    - run: yarn --ignore-scripts
      name: Install dependencies
    - uses: JS-DevTools/npm-publish@v1
      name: Publish
      with:
        package: ./packages/sdk/typescript/human-protocol-sdk/package.json
        access: public
        token: ${{ inputs.token }}
