name: Node.js SDK NPM publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  node-sdk-publish:
    name: Node.js SDK NPM Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --ignore-scripts
        name: Install dependencies
      - name: Change Node.js SDK version
        uses: jossef/action-set-json-field@v2
        with:
          file: ./packages/sdk/typescript/human-protocol-sdkpackage.json
          field: version
          value: ${{ github.event.release.tag_name }}
      - uses: JS-DevTools/npm-publish@v1
        name: Publish
        with:
          package: ./packages/sdk/typescript/human-protocol-sdk/package.json
          access: public
          token: ${{ secrets.NPM_TOKEN }}
