name: Publish packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-version:
    name: Update version in the source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: ${{ github.event.release.tag_name }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Change core version
        uses: jossef/action-set-json-field@v2
        with:
          file: ./packages/core/package.json
          field: version
          value: ${{ github.event.release.tag_name }}
      - name: Change Python SDK version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "version = 0.0.7"
          replace: "version = ${{ github.event.release.tag_name }}"
          include: "./packages/sdk/python/setup.cfg"
          regex: true
      - name: Change Node.js SDK version
        uses: jossef/action-set-json-field@v2
        with:
          file: ./packages/sdk/typescript/human-protocol-sdkpackage.json
          field: version
          value: ${{ github.event.release.tag_name }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "docs(): bumping release ${{ github.event.release.tag_name }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          tags: true
